name: get_it
description: Simple direct Service Locator that allows to decouple the interface from a concrete implementation and  to access the concrete implementation from everywhere in your App"
version: 8.0.0-pre-7
maintainer: Thomas Burkhart (@escamoteur)
homepage: https://github.com/fluttercommunity/get_it
funding:
  - https://github.com/sponsors/escamoteur/
  
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  meta: ^1.9.1

dev_dependencies:
  lint: ^2.1.2
  test: ^1.25.5
